//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesarrolloUnidadTRes.Data.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManoAmigaEntities : DbContext
    {
        public ManoAmigaEntities()
            : base("name=ManoAmigaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmpCatCede> EmpCatCede { get; set; }
        public virtual DbSet<EmpCatEmpleado> EmpCatEmpleado { get; set; }
        public virtual DbSet<EmpCatLicencia> EmpCatLicencia { get; set; }
        public virtual DbSet<EmpCatPuesto> EmpCatPuesto { get; set; }
        public virtual DbSet<EmpCatSexo> EmpCatSexo { get; set; }
        public virtual DbSet<EmpCatStatus> EmpCatStatus { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UniCatAgencia> UniCatAgencia { get; set; }
        public virtual DbSet<UniCatDisponibilidad> UniCatDisponibilidad { get; set; }
        public virtual DbSet<UniCatEdoAgencia> UniCatEdoAgencia { get; set; }
        public virtual DbSet<UniCatTipoUnidad> UniCatTipoUnidad { get; set; }
        public virtual DbSet<Unidades> Unidades { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
